# -*- coding: utf-8 -*-
"""student class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9MIM-hvt0dLYPBxZ6A77Dbz5DkO1YQ-
"""

class Student:
    def __init__(self):
        self.name = ""
        self.roll = 0
        self.marks = 0.0


s1 = Student()

s1.name = "Rahul"
s1.roll = 101
s1.marks = 87.5

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", s1.marks)